### ISSUE TITLE
ASM BIOS

### ISSUE THREAD

**Issue by phoen1s** [web83info/fx-890p#5]
HI i read this : http://stear.c.ooco.jp/fx890p/fxbios.htm . and i need create a DEFCHR$(255)="021E3E1E02" but in asm bios i think is this part:

 
番号 | ： | 41H=ユーザー定義文字フォント格納エリアのトップアドレスを返す
-- | -- | --
入力 | ： | AH=41H
出力 | ： | BX=ユーザー定義文字のフォントが格納されているオフセットアドレス
機能 | ： | ユーザー定義文字(キャラクターコード252～255、「DEFCHR$」で定義される文字)のフォントデータが格納されているオフセットアドレスを返す。セグメントアドレスは0に固定されています。フォントはキャラクターコード252、253、…、255の順に格納されていて、一文字あたり8バイト、計32バイトの領域がある。「DEFCHR$」で指定するデータとは90°のズレがあるので注意のこと。

 but  i cant generate the char designer.
Can you helpme?

**Comment by web83info** [comment]
@phoen1s Hi, do you want to do this in assembly?

```
10 DEFCHR$(255)="021E3E1E0200"
20 PRINT CHR$(255)
```

**Comment by web83info** [comment]
I hope this will help.

```
		ORG		2000H
		MOV		AH, 41H
		INT		41H
		ADD		BX, 24

		MOV		SI,OFFSET CHAR
		MOV		DI,BX
		MOV		CX,8
		REP		MOVSB

		MOV		AH, 01H
		MOV		DL, 255
		INT		41H
		IRET

CHAR:
		DB		000H, 000H, 008H, 01CH
		DB		01CH, 01CH, 03EH, 000H
```

**Comment by ghost** [comment]
thanks for reply i put the code in the casio and i compile but when i run the casio freezer and not respond.

**Comment by web83info** [comment]
I compiled this code on Z-1GR (Actual machine) and worked OK.
Did you run it on emulator?

**Comment by ghost** [comment]
i run in real machine casio z-1gr.

**Comment by web83info** [comment]
I do not know why it did not work for you.
After assemble it, in BASIC mode I did:

```
DEFSEG=0
CALL &H2000
```

**Comment by ghost** [comment]
a ok i try again i put call H2000. let me see. 
YES IT WORK.
thank.
now i try some defchr to see the speed.=) thanks men.

**Comment by web83info** [comment]
OK, I hope everything goes well.
