### ISSUE TITLE
NRS & RFS Z1GR

### ISSUE THREAD

**Issue by phoen1s** [web83info/fx-890p#6]
こちらに書いていますが、動作しないプログラムについて質問したいと思い、あなたにも動作するかどうかを確認し、経験を共有したいと思っています。このプログラムは、CASIOの仮想ハードディスクとしてハードディスクを使用することができ、最初のバージョンはSHARP PC-E500用の仮想ハードディスクを作成していました。PCとCASIOにそれぞれインストールする2つのプログラムで、両方ともMSDOS上で動作します。PCとCASIOのプログラムは正しく起動しますが、PCに接続されません。COM:1ポートを使用していて、すべてはデフォルト設定です。CASIOでDIRコマンドを実行すると、ケーブルがPCに情報を送っているように点灯します。実際にCOOLTERMを有効にすると、CASIOが情報を送信しているのがわかりますが、PCは応答しません。以下のリンクから、これが動作するかどうか、またはどのように動作させるかを確認できます。

公式ページ:
http://stear.c.ooco.jp/fx890p/fx_fxdos.htm#rfs

プログラム名:
FX-DOS Ver1.10用リモートファイルシステムVer0.76

CASIO用プログラム:
http://stear.c.ooco.jp/fx890p/file/RFSFX110.LZH

PC用プログラムURL:
http://stear.c.ooco.jp/etc/file/NRSV_10.LZH

DOSBOXを使っており、DOSBOX-Xも試し、通常は無効になっているCOMポートを設定しました。

もしお時間があれば、ご協力いただけると助かります。
ありがとうございます。

**Comment by web83info** [comment]
当レポジトリは、過去に作成したプログラムを公開するためのもので、新たにプログラムを開発する予定はありません。悪しからず。

**Comment by phoen1s** [comment]
もちろん友よ、ありがとう！結局あまり費用はかからなかったけれど、最終的に手に入れることができました。リンクをここに置いておきますね: https://m.youtube.com/watch?v=3nNTjpKTfk8&t=3s&pp=ygUZQ29uZWN0YXQgY2FkaW8gejFnciBhbCBwYw%3D%3DEl 20 dic 2024, a las 16:58, Web83 ***@***.***> escribió:﻿
Closed #6 as completed.
